apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: il8ly1b8z-nodejs 
  janus-idp.io/tekton: il8ly1b8z-nodejs
  backstage.io/kubernetes-id: il8ly1b8z-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: il8ly1b8z-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml